// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InoxThanhNamServer.Models;

[Table("City")]
public partial class City
{
    [Key]
    public int CityID { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    public int? PostCode { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<District> Districts { get; set; } = new List<District>();

    [InverseProperty("City")]
    public virtual ICollection<UserAddress> UserAddresses { get; set; } = new List<UserAddress>();
}