// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InoxThanhNamServer.Models;

[Table("Contact")]
public partial class Contact
{
    [Key]
    public int ContactID { get; set; }

    [StringLength(255)]
    public string Fullname { get; set; }

    public int Phone { get; set; }

    [StringLength(255)]
    public string Email { get; set; }

    [Column(TypeName = "text")]
    public string Notes { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }
}