// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InoxThanhNamServer.Models;

[Table("Discount")]
public partial class Discount
{
    [Key]
    public int DiscountID { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Code { get; set; }

    public int? Percentage { get; set; }

    public bool Active { get; set; }

    public int? Priority { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [InverseProperty("Discount")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}