// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InoxThanhNamServer.Models;

[Table("District")]
public partial class District
{
    [Key]
    public int DistrictID { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    public int? CityID { get; set; }

    [ForeignKey("CityID")]
    [InverseProperty("Districts")]
    public virtual City City { get; set; }

    [InverseProperty("District")]
    public virtual ICollection<UserAddress> UserAddresses { get; set; } = new List<UserAddress>();

    [InverseProperty("District")]
    public virtual ICollection<Ward> Wards { get; set; } = new List<Ward>();
}