// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InoxThanhNamServer.Models;

[Table("Notification")]
public partial class Notification
{
    [Key]
    public int NotificationID { get; set; }

    public Guid? Receiver { get; set; }

    [Required]
    [StringLength(20)]
    public string Type { get; set; }

    public int? ObjectID { get; set; }

    [Column(TypeName = "ntext")]
    public string Message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReadAt { get; set; }

    [ForeignKey("Receiver")]
    [InverseProperty("Notifications")]
    public virtual User ReceiverNavigation { get; set; }
}