// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InoxThanhNamServer.Models;

public partial class PaymentDetail
{
    [Key]
    public int PaymentID { get; set; }

    public int? OrderID { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Provider { get; set; }

    public int Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("PaymentDetails")]
    public virtual Order Order { get; set; }
}