// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InoxThanhNamServer.Models;

[Table("Product")]
public partial class Product
{
    [Key]
    public int ProductID { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    [Column(TypeName = "ntext")]
    public string Description { get; set; }

    public int? CategoryID { get; set; }

    public int? Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal Price { get; set; }

    public int? Priority { get; set; }

    public int? DiscountID { get; set; }

    [StringLength(255)]
    public string Material { get; set; }

    [StringLength(255)]
    public string Dimension { get; set; }

    [StringLength(255)]
    public string Origin { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeletedAt { get; set; }

    [ForeignKey("CategoryID")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [ForeignKey("DiscountID")]
    [InverseProperty("Products")]
    public virtual Discount Discount { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductReview> ProductReviews { get; set; } = new List<ProductReview>();
}