// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InoxThanhNamServer.Models;

[Table("UserRole")]
public partial class UserRole
{
    [Key]
    public int UserRoleID { get; set; }

    public Guid? UserID { get; set; }

    public int? RoleID { get; set; }

    [ForeignKey("RoleID")]
    [InverseProperty("UserRoles")]
    public virtual Role Role { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("UserRoles")]
    public virtual User User { get; set; }
}